import { Cliente } from "./cliente";

export const CLIENTES: Cliente[] = [
    {
      id: 1,
      nombre: 'Juan',
      apellido: 'Pérez',
      createAt: '2023-01-01',
      email: 'juan.perez@example.com',
    },
    {
      id: 2,
      nombre: 'María',
      apellido: 'Gómez',
      createAt: '2023-02-15',
      email: 'maria.gomez@example.com',
    },
    {
      id: 3,
      nombre: 'Carlos',
      apellido: 'López',
      createAt: '2023-03-10',
      email: 'carlos.lopez@example.com',
    },
    {
      id: 4,
      nombre: 'Ana',
      apellido: 'Rodríguez',
      createAt: '2023-04-20',
      email: 'ana.rodriguez@example.com',
    },
    {
      id: 5,
      nombre: 'Pedro',
      apellido: 'Martínez',
      createAt: '2023-05-05',
      email: 'pedro.martinez@example.com',
    },
    {
      id: 6,
      nombre: 'Laura',
      apellido: 'Sánchez',
      createAt: '2023-06-18',
      email: 'laura.sanchez@example.com',
    },
    {
      id: 7,
      nombre: 'Javier',
      apellido: 'Gutiérrez',
      createAt: '2023-07-03',
      email: 'javier.gutierrez@example.com',
    },
    {
      id: 8,
      nombre: 'Carmen',
      apellido: 'Jiménez',
      createAt: '2023-08-12',
      email: 'carmen.jimenez@example.com',
    },
    {
      id: 9,
      nombre: 'Diego',
      apellido: 'Hernández',
      createAt: '2023-09-25',
      email: 'diego.hernandez@example.com',
    },
    {
      id: 10,
      nombre: 'Isabel',
      apellido: 'Díaz',
      createAt: '2023-10-30',
      email: 'isabel.diaz@example.com',
    },
    {
      id: 11,
      nombre: 'Miguel',
      apellido: 'Alonso',
      createAt: '2023-11-08',
      email: 'miguel.alonso@example.com',
    },
    {
      id: 12,
      nombre: 'Sara',
      apellido: 'Fernández',
      createAt: '2023-12-12',
      email: 'sara.fernandez@example.com',
    },
    {
      id: 13,
      nombre: 'Francisco',
      apellido: 'Morales',
      createAt: '2024-01-15',
      email: 'francisco.morales@example.com',
    },
    {
      id: 14,
      nombre: 'Elena',
      apellido: 'Ortega',
      createAt: '2024-02-28',
      email: 'elena.ortega@example.com',
    },
    {
      id: 15,
      nombre: 'Edda',
      apellido: 'Rodríguez',
      createAt: '2024-03-05',
      email: 'raul.ramirez@example.com',
    },
  ];